### ISSUE TITLE
Game Rules appears clickable but does nothing

### ISSUE THREAD

**Issue by yonatan-ratner** [VideoGameTeam3/Dungeons-and-Rats#1]
like title says, pictures follow:

* unclicked:
![image](https://github.com/VideoGameTeam3/Dungeons-and-Moles/assets/73063105/eb369c6e-8809-4221-bda5-083f4eade187)

* clicked:

![image](https://github.com/VideoGameTeam3/Dungeons-and-Moles/assets/73063105/c29d74e3-9652-45e1-8520-69dcf838f69b)

**Comment by EladLaster** [comment]
תוקן 👍
