### ISSUE TITLE
flashlight explenation text far from object

### ISSUE THREAD

**Issue by ofekrotem** [VideoGameTeam3/Dungeons-and-Rats#10]
![image](https://github.com/VideoGameTeam3/Dungeons-and-Moles/assets/92383710/e862157a-98f8-4926-9288-e3f595d7bd7b)

**Comment by EladLaster** [comment]
תוקן 👍

**Comment by EladLaster** [comment]
תוקן 👍

**Comment by EladLaster** [comment]
תוקן 👍
