### ISSUE TITLE
רמות שאפשר לעקוף

### ISSUE THREAD

**Issue by Michael-Aga** [VideoGameTeam3/Dungeons-and-Rats#12]
רוב הרמות לא צריך להתאמץ ואפשר פשוט לדלג מעל כל המכשולים בלי להסתבך פשוט נמצדים לקיר למעלה כמו כאן
![image](https://github.com/VideoGameTeam3/Dungeons-and-Moles/assets/85742675/ea5823e7-45ec-4181-b117-6b9d4e789611)
בנוסף 7 שניות לרמות בהתחלה זה המון זמן אפשר לעשות שברגע שהשחקן רוצה שיזוז ויגמר הטיימר ויתחיל המשחק

**Comment by EladLaster** [comment]
תוקן 👍
