### ISSUE TITLE
ניקוד או חיים

### ISSUE THREAD

**Issue by Dorshir** [VideoGameTeam3/Dungeons-and-Rats#14]
קצת מבאס שאין ניקוד או חיים, אפשר פשוט לרוץ בכל שלב כמה וכמה פעמים לפני שאתה באמת רוצה להתחיל, וממש לראות איפה המכשולים, מבלי להפסל ממש.. לטעמי כדאי להוסיף חיים היורדים בכל התנגשות, כך שכשנגמרו החיים השחקן יצטרך להתחיל את כל השלבים מהתחלה.

**Comment by EladLaster** [comment]
תוקן 👍
