### ISSUE TITLE
review 

### ISSUE THREAD

**Issue by sagir567** [VideoGameTeam3/Dungeons-and-Rats#15]
1) settings are empty
2) quit crushing the game
3)itch. io resolution doesn't match the unity window resolution, looks bad and buttons might be hidden
4) 2x sprite is missing and doesn't function only text shows on the screen
5) no timer GUI on the later levels
6) The tail makes the player lose even when not touching, should fixed color

**Comment by EladLaster** [comment]
fixed 👍
