### ISSUE TITLE
עונש לכמות פעמים שבהם נפסלים

### ISSUE THREAD

**Issue by MatanAdar** [VideoGameTeam3/Dungeons-and-Rats#18]
המשחק נראה טוב אבל לפי דעתי חסר חיים או כמות פעמים שהשחקן יכול להיפסל, כי כרגע השחקן יכול פשוט להמשיך להיפסל ולחזור להתחלה בלי שום עונש לכמות הפעמים.

**Comment by EladLaster** [comment]
תוקן 👍
