### ISSUE TITLE
יש שלב שאי אפשר לעבור

### ISSUE THREAD

**Issue by itamarc101** [VideoGameTeam3/Dungeons-and-Rats#2]
היה איזה שלב שלא משנה כמה ניסיתי לא הצלחתי לעבור אותו
כמה דגשים - אם נפסלים שתהיה אפשרות לראות שוב את המכשולים כי אפשר לשכוח

**Comment by erelsgl** [comment]
אתה מתכוון לשלב 6? אני הצלחתי לעבור אותו אחרי כ-30 ניסיונות.. זה באמת קשה

**Comment by EladLaster** [comment]
תוקן 👍
