### ISSUE TITLE
השידרוגים לא חוזרים אחרי שנפסלים

### ISSUE THREAD

**Issue by erelsgl** [VideoGameTeam3/Dungeons-and-Rats#20]
אחרי שנפסלים, גם השדרוגים החיוביים וגם השליליים נעלמים ולא חוזרים. אני לא בטוח שזה רעיון טוב: זה אומר שבפעם הבאה שמשחקים, השלב הוא כבר לא אותו שלב - יש בו רק מכשולים בלי שידרוגים, וזה פחות מעניין. במיוחד למי שנפסל הרבה פעמים..

**Comment by EladLaster** [comment]
תוקן 👍
