### ISSUE TITLE
יש שלב שלא ניתן לעבור +העכבר מהפך 

### ISSUE THREAD

**Issue by ohadtaizi** [VideoGameTeam3/Dungeons-and-Rats#7]
יש שלב שבו לקחתי את הגדלה של העכבר אבל גם אחרי שהפסדתי אני נשאר עם ההגדלה כך שאין לי סיכוי לעבור ואם אני בטעות הולך אחורה הכיוון של העכבר משתנה גם אחרי שהוא מפסיד .
לפי דעתי את כל השינויים המתבצעים על העכבר יש להחזיר אחרי ההפסד .
אין הגדרות .

**Comment by EladLaster** [comment]
תוקן 👍
